### ISSUE TITLE
An analyzer

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/sst-filters#2]
would be lovely if this lib contained something like 'set::filters::analyzer(type, subtype, resonance)` which could return you the frequency response for the filter at a given resonance. just an impulse in and dft out or some such. but then we could put dynamic response curves in our uis!

Just a passing thought

**Comment by mkruselj** [comment]
That would be awesome!

I'd call it `getMagnitudePlot()` though.

**Comment by baconpaul** [comment]
yeah or `getFrequencyResponse` or some such

**Comment by jatinchowdhury18** [comment]
Not _quite_ there yet, but I was able to get this working today:

https://user-images.githubusercontent.com/13724188/151716762-9d97388e-e797-4a7f-a7d1-2c70a6f74bbc.mov

**Comment by baconpaul** [comment]
that looks perfect honestly. I can't quite read the screen - that's text output into gnu plot or something? Or do you have a juce plotting library around? (and if you don't, wanna work on a submodule with me :) )

**Comment by jatinchowdhury18** [comment]
The plotting tool here is a `std::vector` going into [matplotlib-cpp](https://github.com/lava/matplotlib-cpp). It's pretty easy to use, but not particularly portable since the user needs to have some Python dependencies installed (and even then, for some reason I can't get past this linking error on my Windows machine...).

It could definitely be cool to work on some JUCE plotting code! I have code for doing frequency domain plots lying around somewhere, but it's pretty hacky...

**Comment by baconpaul** [comment]
Yeah! At least a simple 2d line and scatter plot with a title and axes. I am still amazed that doesn't exist for juce in OSS land but it doesn't. Could be a nice SST library :)

And then we could show all the real filter responses in surge too.

**Comment by baconpaul** [comment]
so anyway the analyzer now works and is deployed in the XT nightly so closing this!
